name: create site.zip archive

on:
  workflow_dispatch:

jobs:
  package-site:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.x

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: install dependencies
        run: pnpm install

      - name: build and bundle site
        run: pnpm site

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: site-archive
          path: _site/site.zip
          overwrite: true
