name: trigger deployment

on:
  workflow_dispatch:

jobs:
  import-data:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.x

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: install dependencies
        run: pnpm install

      - name: empty commit
        run: |
          git config --local user.email "tmk@exidia.com"
          git config --local user.name "Narratio Team Member [via GitHub Action]"
          git commit -m "Manual deployment trigger" --allow-empty

      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
